// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCijmqbIsWzQA3KTnbYynt65QWqRgWeAYk',
    appId: '1:854165679222:web:ea4126e7f6391bc5d44357',
    messagingSenderId: '854165679222',
    projectId: 'discussions-4f196',
    authDomain: 'discussions-4f196.firebaseapp.com',
    storageBucket: 'discussions-4f196.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xb8A1NUcN0IpTxk6mzGY112MI9ac7T0',
    appId: '1:854165679222:android:572bac3aa6138f8bd44357',
    messagingSenderId: '854165679222',
    projectId: 'discussions-4f196',
    storageBucket: 'discussions-4f196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1IdY5szgLk7O204P9RywpXc-p4DbzqAk',
    appId: '1:854165679222:ios:dcc5b811d1b30040d44357',
    messagingSenderId: '854165679222',
    projectId: 'discussions-4f196',
    storageBucket: 'discussions-4f196.appspot.com',
    androidClientId: '854165679222-di490f4i6dvs3rncnqr1n6pq221jarah.apps.googleusercontent.com',
    iosClientId: '854165679222-grglidg8r3jrvlvet69225n8q6uh61oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.discussions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1IdY5szgLk7O204P9RywpXc-p4DbzqAk',
    appId: '1:854165679222:ios:549f0fea8a27fc0bd44357',
    messagingSenderId: '854165679222',
    projectId: 'discussions-4f196',
    storageBucket: 'discussions-4f196.appspot.com',
    androidClientId: '854165679222-di490f4i6dvs3rncnqr1n6pq221jarah.apps.googleusercontent.com',
    iosClientId: '854165679222-ip39rf4ghdnr101700jbef9vv207747v.apps.googleusercontent.com',
    iosBundleId: 'com.example.discussions.RunnerTests',
  );
}
